#!/usr/bin/env python3
# Generated by Phi3 Agent
# Model: phi3:mini
# Task: Write a function to add two numbers

```python

# Define the function 'add_two_numbers' that takes in two parameters (num1 and num2)

def add_two_numbers(num1, num2):

    """Adds two numbers together."""

    # Return the sum of the two numbers

    return num1 + num2

```