#!/usr/bin/env python3
# Generated by Kimi Cloud Agent
# Model: kimi-code
# Task: write a python hello world

# hello_world.py
# A simple Hello World program in Python

def main():
    """Prints a greeting message to the console."""
    print("Hello, World!")

# Run the main function when the script is executed directly
if __name__ == "__main__":
    main()