#!/usr/bin/env python3
# Generated by Phi3 Agent
# Model: phi3:mini
# Task: Write a Python function to reverse a string

```python
def reverse_string(s):
    # Initialize an empty result string
    reversed_str = ""
    
    # Loop through the original string in reverse order and append each character to the result string
    for char in s[::-1]:
        reversed_str += char
        
    return reversedener str  # Return the reversed string

# Test the function with a sample input
original_string = "Hello, World!"
reversed_string = reverse_string(original_string)
print("Original String:", original_string)
print("Reversed String:", reversed_string)
```