#!/usr/bin/env python3
# Generated by Phi3 Agent
# Model: phi3:mini
# Task: Write DocumentChunker class for splitting documents. Output ONLY the code/content.

```python

class DocumentChunker:

    def __init__(self, document_path):

        """Initialize with a file path to the document."""

        self.document_path = document end="""

        def chunk(self, size=10):

            """Split the document into chunks of specified size (default is 10)."""

            try:

                with open(self.document_path, 'r') as file:

                    content = file.read()

                    for i in range(0, len(content), size):

                        yield chunk := content[i:i+size]  # Yield chunks of the specified size

            except FileNotFoundError:

                print("The document was not found.")

        
    def process_documents(self, file_paths, size=10):

        """Process multiple documents."""

        for path in file_paths:

            self.document_path = path  # Set the current document's path

            try:

                chunks = list(self.chunk(size))  # Get all chunks of this size from the current document

                print(f"Document {path} processed into {len(chunks)} parts.")

                for i, chunk in enumerate(chunks):

                    yield f"Chunk {i+1}: {chunk}"  # Yield each part with its index number.

            except FileNotFoundError:

                print(f"The document at path '{path}' was not found.")

```